#!/bin/env python
import json
import sys
from multiprocessing import Pool


def sort_j(j):
    input_file = j
    output_file = "sorted_{0}".format(input_file)

    with open(input_file) as fd:
        with open(output_file, "w") as ofd:
            json.dump(json.load(fd), ofd, indent=4, sort_keys=True)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Plz provide json files to be key sorted.")
    pool = Pool()  # by default using multiprocessing.cpu_count()
    pool.map(sort_j, sys.argv[1:])
